# Generated by Django 5.0.7 on 2024-07-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_actor_movieinfo_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='actors',
            field=models.ManyToManyField(related_name='acted_movies', to='movies.actor'),
        ),
    ]
